### ISSUE TITLE
Questions about Environment requirements

### ISSUE THREAD

**Issue by judgingalready** [m-Just/OoD-Bench#2]
Hi, thanks for your great work!

There are some questions about environment requirements in your benchmark. I use your benchmark to run **ERM** in several datasets, while all performences are lower 1%-2% than the results in the paper, so I think it may be caused by the environment. Then I try to follow the requirements.txt, but get this:

```
ERROR: Cannot install -r requirements.txt (line 6) and torch==1.10.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.10.2
    torchvision 0.11.2 depends on torch==1.10.1
```

I also find the correspondence between torch and torchvision in [https://github.com/pytorch/vision#installation](https://github.com/pytorch/vision#installation). I am not sure if it's a mistake, and I hope to know more detailed virtual environment requirements in your benchmark with OoD algorithms. Thanks a lot.

**Comment by m-Just** [comment]
Hi, thank you for reporting this! You can use the corresponding version of torchvision (0.11.3). It should be fine.
I was using an old version of pip, so this conflict was not reported and unnoticed.

**Comment by judgingalready** [comment]
Thanks for your reply !
